name: 'Power ON or DEALLOCATE a specific Azure VM'
description: 'This action either powers on or powers off (deallocates) a specific Azure VM'

branding:
  icon: download
  color: blue

inputs:
  POWER_SWITCH:
    description: 'Turn ON or OFF the VM'
    required: true
  AZURE_VM_NAME:
    description: 'Name of the VM'
    required: true
  AZURE_RG_NAME:
    description: 'Resource Group where the VM lives'
    required: true
  AZURE_SP_CLIENTID:
    description: 'Service Principal ClientID'
    required: true
  AZURE_SP_SECRET:
    description: 'Service Principal Secret'
    required: true
  AZURE_TENANTID:
    description: 'Service Principal TenantID'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Login with az CLI"
      shell: pwsh
      run: |
        az login --service-principal -u ${{ inputs.AZURE_SP_CLIENTID }} -p ${{ inputs.AZURE_SP_SECRET }} --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
    
    - name: 'Debug POWER'
      shell: pwsh
      run: |
        echo POWER_SWITCH

    - name: "Deallocate VM"
      shell: pwsh
      if: ${{ inputs.POWER_SWITCH == 0 }}
      run: | 
        az vm deallocate --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 

    - name: "Start VM"
      shell: pwsh
      if: ${{ inputs.POWER_SWITCH == 4 }}
      run: | 
        az vm start --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 