name: FULL workflow

on:
  workflow_dispatch:
    inputs:
      vm_name:
        required: true
        type: string
        description: The name of the VM
      rg_name:
        required: true
        type: string
        description: The name of the resource-group the VM belongs to
      on_off:
        required: true
        type: choice
        description: Turn VM ON or OFF
        options:
          - ON
          - OFF

jobs:
  call-workflow:
    uses: roel4ez/action-power-on-off-azure-vm/.github/workflows/power-on-azure-vm.yml@main
    if: ${{ github.events.inputs == 'ON' }}
    with:
      AZURE_VM_NAME: ${{ github.event.inputs.vm_name }}
      AZURE_RG_NAME: ${{ github.event.inputs.rg_name }}
    secrets:
      AZURE_SP_CLIENTID: ${{ secrets.AZURE_SP_CLIENTID }}
      AZURE_SP_SECRET: ${{ secrets.AZURE_SP_SECRET }}
      AZURE_TENANTID: ${{ secrets.AZURE_TENANTID }}
    uses: roel4ez/action-power-on-off-azure-vm/.github/workflows/power-on-azure-vm.yml@main
    if: ${{ github.events.inputs == 'OFF' }}
    with:
      AZURE_VM_NAME: ${{ github.event.inputs.vm_name }}
      AZURE_RG_NAME: ${{ github.event.inputs.rg_name }}
    secrets:
      AZURE_SP_CLIENTID: ${{ secrets.AZURE_SP_CLIENTID }}
      AZURE_SP_SECRET: ${{ secrets.AZURE_SP_SECRET }}
      AZURE_TENANTID: ${{ secrets.AZURE_TENANTID }}
