name: Main workflow

on:
  workflow_dispatch:
    inputs:
      power:
        required: true
        description: 'Turn the VM ON or OFF'
        type: boolean
      vm_name:
        description: 'the name of the vm to be turned on'
        required: true 
        default: 'vm-test-gh-action'
        type: string
      rg_name:
        required: false
        type: string
        default: 'vm-test'
        description: 'the name of the resource-group the VM belongs to'

jobs:
  power_azure_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Power Azure VM
        uses: roel4ez/power-azure-vm@main
        with:
          AZURE_VM_NAME: ${{ github.event.inputs.vm_name }}
          AZURE_RG_NAME: ${{ github.event.inputs.rg_name }}
          POWER: ${{ github.event.inputs.power }}