name: Main workflow

on:
  workflow_dispatch:
    inputs:
      power:
        required: true
        description: 'Turn the VM ON or OFF'
        type: choice
        options:
          - 'ON'
          - 'OFF'
      vm_name:
        description: 'the name of the vm to be turned on'
        required: true 
        default: 'vm-test-gh-action'
        type: string
      rg_name:
        required: false
        type: string
        default: 'vm-test'
        description: 'the name of the resource-group the VM belongs to'

jobs:
  call-workflow:
    uses: roel4ez/action-power-on-off-azure-vm/.github/workflows/power-vm-azure.yml@main
    with:
      AZURE_VM_NAME: ${{ github.events.input.vm_name }}
      AZURE_RG_NAME: ${{ github.events.input.rg_name }}
      POWER: ${{ github.events.input.power }}
    secrets:
      AZURE_SP_CLIENTID: ${{ secrets.AZURE_SP_CLIENTID }}
      AZURE_SP_SECRET: ${{ secrets.AZURE_SP_SECRET }}
      AZURE_TENANTID: ${{ secrets.AZURE_TENANTID }}