name: Set Azure VM on

on:
  workflow_call:
    inputs:
      AZURE_VM_NAME:
        required: true
        type: string
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      # this doesn't work
      # - uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az login --service-principal -u ${{ secrets.AZURE_SP_CLIENTID }} --p ${{ secrets.AZURE_SP_SECRET }} --tenant ${{ secrets.AZURE_TENANTID }}  |
          az vm start --name ${{ github.event.inputs.AZURE_VM_NAME }} --no-wait 
