name: Set Azure VM ON or OFF

on:
  workflow_call:
    inputs:
      POWER:
        required: true
        type: boolean
      AZURE_VM_NAME:
        required: true
        type: string
      AZURE_RG_NAME:
        required: true
        type: string
    secrets:
      AZURE_SP_CLIENTID:
        required: true
      AZURE_SP_SECRET:
        required: true
      AZURE_TENANTID:
        required: true
        
jobs:
  azure_vm:
    runs-on: ubuntu-latest
    steps:
      - name: "Login with az CLI"
        run: |
          az login --service-principal -u ${{ secrets.AZURE_SP_CLIENTID }} --p ${{ secrets.AZURE_SP_SECRET }} --tenant ${{ secrets.AZURE_TENANTID }}
      
      - name: "Deallocate VM"
        if: ${{ !inputs.POWER }}
        run: | 
          az vm deallocate --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 

      - name: "Start VM"
        if: ${{ inputs.POWER }}
        run: | 
          az vm start --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 
