name: Set Azure VM on

on:
  workflow_call:
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az vm start --name ${{ secrets.AZURE_VM_NAME }} --no-wait 
