name: Set Azure VM on

on:
  workflow_call:
    inputs:
      AZURE_VM_NAME:
        required: true
        type: string
      AZURE_RG_NAME:
        required: true
        type: string
    secrets:
      AZURE_SP_CLIENTID:
        required: true
      AZURE_SP_SECRET:
        required: true
      AZURE_TENANTID:
        required: true
        
jobs:
  start_azure_vm:
    runs-on: ubuntu-latest
    steps:
      - name: "Login with az CLI"
        run: |
          az login --service-principal -u ${{ secrets.AZURE_SP_CLIENTID }} --p ${{ secrets.AZURE_SP_SECRET }} --tenant ${{ secrets.AZURE_TENANTID }}
      - name: "Start VM"
        run: | 
          az vm start --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ AZURE_RG_NAME }} --no-wait 
